#! /bin/sh
### BEGIN INIT INFO
# Provides:          camcam
# Required-Start:    $local_fs ram_fs
# Required-Stop:
# Default-Start:     S
# Default-Stop:         0 6
# Short-Description: Image acquisition loop.
### END INIT INFO

PATH="/sbin:/bin:/usr/bin"
PID_FILE=/var/run/camcam.pid
MYDIR=/home/pi/rpi_boot_camp/webcam
CMD=$MYDIR/image_acquisition/image_loop.py
PYTHON=/usr/bin/python

. /lib/lsb/init-functions

do_start () {
    /sbin/start-stop-daemon --start --chuid pi -d $MYDIR --background -v --user pi --pidfile $PID_FILE --make-pidfile --exec $PYTHON --startas $PYTHON -- $CMD
    log_success_msg "Started camcam"
}
do_stop () {
    /sbin/start-stop-daemon --stop -d $MYDIR -v --user pi --pidfile $PID_FILE --exec $PYTHON --retry 10
    rm $PID_FILE
    log_success_msg "Stopped camcam"
}

case "$1" in
  start)
        do_start
        ;;
  restart|reload|force-reload)
        do_stop || log_failure_msg "Not running"
        do_start
        ;;
  stop|status)
        do_stop
        ;;
  *)
        echo "Usage: $0 start|stop" >&2
        exit 3
        ;;
esac
