#! /bin/sh
### BEGIN INIT INFO
# Provides:          camcam
# Required-Start:    $local_fs ram_fs
# Required-Stop:
# Default-Start:     S
# Default-Stop:         0 6
# Short-Description: Prepares RAM file system for cam.
### END INIT INFO

PATH=/sbin:/bin
PID_FILE=/var/run/web2py.pid
MYDIR=/home/pi
CMD=$MYDIR/web2py/web2py.py
PYTHON=/usr/bin/python

. /lib/lsb/init-functions

do_start () {
    /sbin/start-stop-daemon --start --chuid pi -d $MYDIR --background -v --user pi --pidfile $PID_FILE --make-pidfile --exec $PYTHON --startas $CMD -- -a banana -p 8888 -i 0.0.0.0
    log_success_mgs "Started web2py"
}
do_stop () {
    /sbin/start-stop-daemon --stop -d $MYDIR -v --user pi --pidfile $PID_FILE --exec $PYTHON --retry 10
    rm $PID_FILE
    log_success_msg "Stopped web2py"
}

case "$1" in
  start)
        do_start
        ;;
  restart|reload|force-reload)
        do_stop || log_failure_msg "Not running"
        do_start
        ;;
  stop|status)
        do_stop
        ;;
  *)
        echo "Usage: $0 start|stop" >&2
        exit 3
        ;;
esac